INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'CF FT 410', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'CF85 FT 410A', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FT 480', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FT 480 SSC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FT 530', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FTS 480', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FTS 530 SSC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FTT 480', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FTT 530', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF FTT 530 SSC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF105 FTS 460A', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF105 FTT 460A', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('DAF', 'XF105 FTT 510A', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 1621', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 1622', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2042 AT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2425', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2428 CNL', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2428 E', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2428E', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2429L', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2431 l', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2629 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2842 AT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 2932 E', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 4331', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 4532 E', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 4532E TOPLINE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CARGO 6332E', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'CHAPEMEC CARGO', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('FORD', 'F14000', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('I/MO', 'GROVE GMK5250L', 'crane');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('I/MO', 'XCMG QY 70K -I', 'crane');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IMO XCMG', 'QY 50K', 'crane');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('INTERNACIONAL', '9800P7 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('INTERNATIONAL', '9800 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('INTERNATIONAL', '9800 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('INTERNATIONAL', '9800I 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('INTERNATIONAL', '9800I 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'EUROTECH 450E37TN1', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'CAVALLINO 450E32T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'CURSOR 450E32T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'CURSOR 450E33T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'ECCURSOR 450E32TN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'FIAT E 450E3HT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIHD 450S38TN1', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIHD 490S38TN1', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIHD 570S38TN1', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIHD 570S42TN1', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIHD 740S42TZN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIHD 740S46TZ', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 450S33T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 460S36T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 490S38T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 490S40T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 490S41T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 490S44T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 490S46T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 490S48T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS 800S56TZ', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALISHD 450S38T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALISHD 450S38TN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALISHD 490S38TN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALISHD 490S46T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALISHD 570S38TN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALISHD 570S42TN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'S-WAY 480-4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'S-WAY 480-6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'S-WAY 540-6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TECTOR 240E28', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TECTOR 310E30CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TRAKKER 380T42N', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TRAKKER 410T48', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TRAKKER 480T42N', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TRAKKER 720T42TN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'TRAKKER 740T48T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'STRALIS HD 740S42TZ', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('IVECO', 'RURAL COTTON TRANSP E CORRETAGEM AGRIC L', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'L 2638', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2730 CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2045S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2651LS6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2651S6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS2646LS6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2425', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 1933 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2040 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2041 LS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2535 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2544 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2644 LS 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2644S6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 33446X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 3344S6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '2418', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '1728 TRUKAM CA', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '1938 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '1944 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '2038 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '2423 K', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', '2726 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACCELO 815 CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2546LS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2548S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2553S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2646LS6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2646S6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2648S 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2651S 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ACTROS 2653S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 1726', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 1726 CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2426', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2428', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2429', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2730 6X4 CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2730 6X4 CL', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 2730CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 3030 CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 3033CE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATEGO 3330', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATRON 1635 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'ATRON 2729 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 1933', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 1933 GNG S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2035 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2036 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2040', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2041 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2044 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2533', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2536 LS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2540 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2541 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2544S ASTER', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 2641S6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 28316X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 3131 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 33406X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR 3340S6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'AXOR LOC TRATOR', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'L 1620', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'L 1621', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'L 2220', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'LK 2318', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'LS 1634', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'LS 1935', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'LS 1941', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'LS 2638', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('M.BENZ', 'LUCIANE', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('MAN', 'TGX 28.440 6X2 T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('MAN', 'TGX 29.440 6X4 T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('MAN', 'TGX 29.480 6X4 T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('MAN', 'TGX 33.440 6X4 T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('MERCEDES-BENZ', 'ACTROS 2651S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('NAVISTAR', 'INTERN 9800 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 360 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 380 A4x2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 380 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 400 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 400 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 420 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 420 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 420 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 420 B6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 440 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 440 A6X4 CS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 440 B6X4 CS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 470 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 480 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G 480 A6X4 CS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G370 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G370 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G410 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G410 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G420 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G450 A6X4 XT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G540 A6X4 XT CS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'G560 A6X4 XT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'L111', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'LK 111', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 250 B6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 250 B6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 270 B6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 310 B6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 310 B6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 310 B8X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 340 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 340 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 360 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 360 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 360 B6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 360 B6X4 CS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P 420 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P114GA4X2NZ 330', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P114GA4X2NZ 340', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P114GA4X2NZ 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P124CA6X4NZ 400', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P124CA6X4NZ 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P124CB6X4NZ 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P124CB8X4NZ 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P124GA4X2NZ 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P360 B8X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'P370 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 113 H 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 124 LA6X2NA 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 380 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 400 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 410 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 420 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 420 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 420 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 440 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 440 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 440 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 460 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 470 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 470 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 480 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 500 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 560 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R 620 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R112 H 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R112 MA4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R113 H 4X2 320', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R113 H 4X2 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R114 GA4X2NZ 320', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R114 GA4X2NZ 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R114 GANZ 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R114 LA6X2NA 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R114GA4X2NZ 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 GA4X2NZ 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 GA4X2NZ 400', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 GA4X2NZ 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 GA6X4NZ 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 GA6X4NZ 400', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 GA6X4NZ 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 LA4X2NA 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 LA4X2NA 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 LA6X2NA 400', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R124 LA6X2NA 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R164GA6X4NZ 480', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R410 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R450 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R450 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R450 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R460 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R460 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R500 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R510 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R540 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R540 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R560 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'R620 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'S450 A4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'S450 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'S460 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'S500 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'S540 A6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'S560 A6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T112 H 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T112 HS 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T112 HW 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T113 H 4X2 310', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T113 H 4X2 320', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T124 GA4X2NZ 360', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T124 GA6X4NZ 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SCANIA', 'T142 H 4X2 S', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SINOTRUCK', 'A7 H6X4 460A', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SINOTRUCK', 'HOWO 6X2 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('SINOTRUCK', 'HOWO 6X4 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', 'VM 270 8X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '18. 310 TITAN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '18.310 TITAN', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.320 CLC TT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.320 CNC TT', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.330 CTC 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.360 CTC 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24. 330 CRC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24.280 CRM 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24.330 CRC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '25.370 CNM T 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '25.390 CTC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '25.420 CTC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '26.390 CTC 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '29.520 METEOR 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '33.460 CTM 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '13.130', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24.320 CLC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '31.330 CRC 6X4 CMT 63 (Nome Oficial: 31.330 CRC 6X4)', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', 'VW 31.280 CRM 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.370 CLM T 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.390 CTC 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '19.420 CTC 4x2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '25.320 CNC T 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '26.420 CTC 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '9.150 E-CUMIS', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', 'BMB 25.320 CNC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '8.160 DRC 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '32.360 CRC 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '17.300', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '23.220', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '26.300', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '40.300', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '15.190 CRM 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '20.480 CTM 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24.250 CNC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24.250 MASTER', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '24.320 CLC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '25.360 CTC 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '25.370 CLM T 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '28.480 MTM 6X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '29.530 MTM 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '31.280 CRM 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '31.320 CRM 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '31.330 CRC 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '32.380 CRC 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '33.480 CTM 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('V.W', '26.370 CLM T 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 380 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 400 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 460 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 460 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 480 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 500 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 520 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 540 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', '310 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 400 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 400 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 420 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 440 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 440 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 440 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 440 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 440 GER', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 460 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 460 6X4T SUSP', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 480 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 500 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 500 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 540 6X4T SUSP', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 540 MASTER', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH 8X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 380', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 380 4X2 T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 380 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 380 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 380 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 420', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 420 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 420 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 420 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 420 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 460 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FH12 460 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 370 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 370 6X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 400 6X4R GERM', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 440 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 440 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 460 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 480 6X4', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 480 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 480 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 500 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 540 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM 540 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM12 340 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM12 380 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM12 420 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'FM12 420 6X4T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'N10', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'N10 HT IC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NH12380 4X2 T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NH12380 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NL10 340', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NL10 340 4X2', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NL12 360 4X2T EDC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NL12 400', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'NL12 410 4X2T EDC', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 260 6X2R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 290 6X4 R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 310 4X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 310 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 330 6X4R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 330 8X2R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 330 8X2T', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 360 6x2 R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 360 6X4 R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM 360 8X2 R', 'tractor_unit');
INSERT INTO vehicle_models (brand, model, vehicle_type) VALUES ('VOLVO', 'VM330 6X2R', 'tractor_unit');